---
header:
  - license:
      spdx-id: Apache-2.0
      copyright-owner: koffloader-io
      pattern: |
        Copyright|Apache-2.0
      content: |
        Copyright 2024 Authors of koffloader-io
        SPDX-License-Identifier: Apache-2.0
    paths:
      - '**/*.go'
      - '**/*.sh'
    paths-ignore:
      - 'vendor'
      - 'pkg/k8s'
      - 'api'
    comment: on-failure
