{{- if .Values.koffloaderAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.koffloaderAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.koffloaderAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.koffloaderAgent.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.koffloaderAgent.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.koffloaderAgent.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- if .Values.koffloaderController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.koffloaderController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.koffloaderController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.koffloaderController.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.koffloaderController.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.koffloaderController.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
