{{- if .Values.koffloaderAgent.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.koffloaderAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.global.commonAnnotations .Values.koffloaderAgent.service.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.koffloaderAgent.service.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.koffloaderAgent.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- include "project.koffloaderAgent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.koffloaderAgent.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.koffloaderAgent.prometheus.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "project.koffloaderAgent.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.koffloaderController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.global.commonAnnotations .Values.koffloaderController.service.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.koffloaderController.service.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.koffloaderController.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- include "project.koffloaderController.labels" . | nindent 4 }}
spec:
  type: {{ .Values.koffloaderController.service.type }}
  ports:
    {{- if .Values.koffloaderController.prometheus.enabled }}
    - name: metrics
      port: {{ .Values.koffloaderController.prometheus.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    - name: webhook
      port: {{ .Values.koffloaderController.webhookPort }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "project.koffloaderController.selectorLabels" . | nindent 4 }}
